# Generated by Django 4.2.19 on 2025-02-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalData',
            fields=[
                ('id', models.UUIDField(db_column='ID', primary_key=True, serialize=False)),
                ('source_site', models.TextField(db_column='Source Site')),
                ('crime_title', models.TextField(db_column='Crime Title', null=True)),
                ('charge_description', models.TextField(db_column='Charge Description', null=True)),
                ('police_department', models.TextField(db_column='Police Department', null=True)),
                ('name', models.TextField(db_column='Name', null=True)),
                ('age', models.TextField(db_column='Age', null=True)),
                ('dob', models.TextField(db_column='Date Of Birth', null=True)),
                ('gender', models.TextField(db_column='Gender', null=True)),
                ('race', models.TextField(db_column='Race', null=True)),
                ('height', models.TextField(db_column='Height', null=True)),
                ('weight', models.TextField(db_column='Weight', null=True)),
                ('city', models.TextField(db_column='City', null=True)),
                ('address', models.TextField(db_column='Address', null=True)),
                ('arrest_date', models.TextField(db_column='Arrest Date', null=True)),
                ('release_date', models.TextField(db_column='Release Date', null=True)),
                ('prisoner_type', models.TextField(db_column='Prisoner Type', null=True)),
                ('classification_level', models.TextField(db_column='Classification Level', null=True)),
                ('housing_facility', models.TextField(db_column='Housing Facility', null=True)),
                ('total_bond_amount', models.TextField(db_column='TotalBondAmount', null=True)),
                ('total_bail_amount', models.TextField(db_column='TotalBailAmount', null=True)),
                ('published_date', models.TextField(db_column='Published Date', null=True)),
                ('image', models.TextField(db_column='Image', null=True)),
                ('url', models.TextField(db_column='URL', null=True)),
            ],
            options={
                'db_table': 'criminal_records',
            },
        ),
    ]
