# Generated by Django 4.2.19 on 2025-03-23 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminaldata',
            name='assigned_to',
            field=models.TextField(db_column='Assigned To', null=True),
        ),
        migrations.AddField(
            model_name='criminaldata',
            name='c_id',
            field=models.IntegerField(db_column='C_ID', default=0),
        ),
        migrations.AddField(
            model_name='criminaldata',
            name='created_at',
            field=models.DateField(db_column='Created_At', default=datetime.date(2025, 3, 23)),
        ),
        migrations.AlterModelTable(
            name='criminaldata',
            table='criminal_data',
        ),
    ]
